spring:
  application:
    name: spring-oauth2-client
  security:
    oauth2:
      client:
        registration:
          custom-client:
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/custom-client'
            scope: read,openid,profile
            provider: custom
        provider:
          custom:
            authorization-uri: http://auth-server:9000/oauth2/authorize
            token-uri: http://auth-server:9000/oauth2/token
            jwk-set-uri: http://auth-server:9000/oauth2/jwks

logging:
  level:
    root: TRACE